// Generated by https://quicktype.io

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResetResponse
    {
        [JsonProperty("responseDesc")]
        public string ResponseDesc { get; set; }

        [JsonProperty("iv")]
        public string Iv { get; set; }

        [JsonProperty("key")]
        public string Key { get; set; }
    }

    public partial class ResetResponse
    {
        public static ResetResponse FromJson(string json) => JsonConvert.DeserializeObject<ResetResponse>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ResetResponse self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
